[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# THESE TWO LINES ARE REQUIRED FOR LITTLEFS TO WORK
; SPIFFS Configuration
board_build.filesystem = spiffs
board_build.partitions = default.csv
 

; Upload settings
upload_speed = 921600
monitor_filters = esp32_exception_decoder

lib_deps =
    mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display @ ^3.0.12
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.14.5

build_flags =
     -std=gnu++17